# Step 01 : KNN Regressor

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.tail()

Gender     Height      Weight
8550  Female  60.483946  110.565497
8551  Female  63.423372  129.921671
8552  Female  65.584057  155.942671
8553  Female  67.429971  151.678405
8554  Female  60.921791  131.253738

In [5]:
from sklearn.preprocessing import LabelEncoder

In [6]:
le = LabelEncoder()

In [7]:
df.Gender = le.fit_transform(df['Gender'])

In [8]:
df.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [9]:
from sklearn.model_selection import train_test_split

x = df[['Gender','Height']]
y = df[['Weight']]

In [10]:
xtrain,xtest, ytrain,ytest=train_test_split(x,y,test_size=.30)

In [11]:
x.head()

Gender     Height
0       1  73.847017
1       1  68.781904
2       1  74.110105
3       1  71.730978
4       1  69.881796

# Linear Regression

In [12]:
from sklearn.linear_model import LinearRegression

In [13]:
reg = LinearRegression()

In [14]:
reg.fit(xtest, ytest)

LinearRegression()

In [15]:
accu = reg.score(xtest, ytest)

In [16]:
accu

0.9064809754046005

In [17]:
m = reg.coef_

In [18]:
c = reg.intercept_

In [19]:
reg.predict([[1,73.847017]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[215.79322818]])

In [20]:
prd = reg.predict(xtest)
from sklearn.metrics import mean_squared_error
mse = mean_squared_error(ytest, prd)

In [21]:
mse

101.45765371546955

In [22]:
from sklearn.metrics import mean_absolute_error
mae = mean_absolute_error(ytest, prd)

In [23]:
mae

8.091220866745223

In [24]:
prd1 = reg.predict(xtrain)
mse1 = mean_squared_error(ytrain, prd1)

In [25]:
mse1

103.65235572919416

In [26]:
mae1 = mean_absolute_error(ytrain, prd1)

In [27]:
mae1

7.999656664255707

# KNN Regression

In [28]:
from sklearn.neighbors import KNeighborsRegressor

In [29]:
nei = KNeighborsRegressor(n_neighbors=10)
nei.fit(xtest, ytest)

KNeighborsRegressor(n_neighbors=10)

In [30]:
knn = nei.predict([[1,73.847017]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsRegressor was fitted with feature names
  warnings.warn(


In [31]:
knn

array([[213.93346488]])

In [32]:
accu1 = nei.score(xtest, ytest)

In [33]:
accu1

0.9147692242563504

In [34]:
xtest.head()

Gender     Height
8249       0  63.807252
2819       1  71.566517
1227       1  69.195298
7694       0  59.413107
2415       1  68.925309

In [35]:
prd2 = nei.predict(xtest)
mse2 = mean_squared_error(ytest, prd2)

In [36]:
mse2

92.46583322176171

In [37]:
xtrain.head()

Gender     Height
6312       0  64.051236
543        1  72.131990
2514       1  70.704094
3414       1  67.901515
5383       0  63.684698

In [38]:
prd3 = nei.predict(xtrain)
mse3 = mean_squared_error(ytrain, prd3)

In [39]:
mse3

115.0574551323275

In [40]:
mae3 = mean_absolute_error(ytrain, prd3)

In [41]:
mae3

8.454829130537242

In [48]:
#plt.bar([accu]), color = 'red')

# Step 02 : KNN Classifier

In [49]:
df2 = pd.read_csv('weight-height.csv')

In [50]:
df2.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [51]:
df2.Gender = le.fit_transform(df['Gender'])

In [52]:
df2.head()

Gender     Height      Weight
0       1  73.847017  241.893563
1       1  68.781904  162.310473
2       1  74.110105  212.740856
3       1  71.730978  220.042470
4       1  69.881796  206.349801

In [53]:
x1 = df[['Height','Weight']]
y1 = df[['Gender']]

In [55]:
x1.head()

Height      Weight
0  73.847017  241.893563
1  68.781904  162.310473
2  74.110105  212.740856
3  71.730978  220.042470
4  69.881796  206.349801

In [56]:
y1.head()

Gender
0       1
1       1
2       1
3       1
4       1

In [57]:
x1train,x1test, y1train,y1test=train_test_split(x1,y1,test_size=.30)

In [58]:
from sklearn.neighbors import KNeighborsClassifier

In [59]:
neigh = KNeighborsClassifier(n_neighbors=10)
neigh.fit(x1test, y1test)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\neighbors\_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=10)

In [60]:
knn1 = neigh.predict([[73.847017,241.893563]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [61]:
knn1

array([1])

In [62]:
knn1 = neigh.predict([[58.91073204,102.0883264]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [63]:
knn1

array([0])

In [64]:
knn1 = neigh.predict([[64,129]])

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but KNeighborsClassifier was fitted with feature names
  warnings.warn(


In [65]:
knn1

array([0])

In [66]:
from sklearn.metrics import classification_report, accuracy_score, confusion_matrix,  plot_roc_curve